services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: flask run --host=0.0.0.0 --port=5000

  ui:
    build:
      context: ./ui
    working_dir: /app
    command: npm run preview -- --port 3000
    ports:
      - "3000:3000"
    depends_on:
      - api
